something = input('Digite algo ')
print('Tipo de dado', type(something))
print('É alfanumérico?', something.isalnum())
print('É alfabético?', something.isalpha())
print('É decimal?', something.isdecimal())
print('É só espaços?', something.isspace())
print('Esta em letras maiúsculas?', something.isupper())
print('Está em letras minúsculas?', something.islower())
print('Está capitalizada?', something.istitle())